name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
    - name: Code Coverage
      uses: mattpolzin/swift-codecov-action@0.3.0
